vpn-data:
    image: busybox:latest
    container_name: vpn-data
    volumes:
# map in the openvpn dir unless you feel like rebuilding
    - /etc/openvpn

vpn:
#    image: annixa/dockerlab-vpn:latest
    build: openvpn
    container_name: vpn
    volumes_from:
    - vpn-data
# override the bin for dev
#    volumes:
#    - ./openvpn/bin:/usr/local/bin
# override the command for dev
#    command: tail -f /dev/null
    ports:
    - "1194:1194/udp"
    cap_add:
    - NET_ADMIN

