vpn:
#    image: annixa/dockerlab-vpn:latest
    build: openvpn
    container_name: vpn
#    volumes:
#    - ./pki:/etc/openvpn/pki
# override the bin for dev
#    - ./openvpn/bin:/usr/local/bin
# override the command for dev
#    entrypoint: sudo
#    command: tail -f /dev/null
    ports:
    - "1194:1194/udp"
    cap_add:
    - NET_ADMIN

